### ISSUE TITLE
typo in error msg

### ISSUE THREAD

**Issue by ericloud** [c3g/GenPipes_Docs#236]
Hi, 

It seems that genpipes 4.4.1 (available on compute canada cluster) have a typo: 
 - `markname = line['MarkName']`
 - and after you use `mark_name` severals times.

More details below:
```
Traceback (most recent call last):
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/pipelines/chipseq/chipseq.py", line 2063, in <module>
    ChipSeq(protocol=['chipseq', 'atacseq'])
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/pipelines/chipseq/chipseq.py", line 89, in __init__
    super(ChipSeq, self).__init__(protocol)
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/pipelines/common.py", line 127, in __init__
    super(Illumina, self).__init__(protocol)
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/pipelines/common.py", line 60, in __init__
    super(MUGQICPipeline, self).__init__()
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/core/pipeline.py", line 175, in __init__
    self.create_jobs()
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/core/pipeline.py", line 386, in create_jobs
    jobs = step.create_jobs()
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/pipelines/chipseq/chipseq.py", line 1252, in differential_binding
    if self.contrasts:
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/pipelines/chipseq/chipseq.py", line 151, in contrasts
    self._contrast = parse_chipseq_design_file(self.args.design.name, self.samples)
  File "/cvmfs/soft.mugqic/CentOS6/software/genpipes/genpipes-4.4.1/core/design.py", line 91, in parse_chipseq_design_file
    _raise(SanitycheckError("Error: invalid value for sample " + sample_name + " and MarkName " + mark_name
NameError: name 'mark_name' is not defined
```

**Comment by MareikeJaniak** [comment]
Hi Eric, 
Apologies about the delayed response. Please note that this github repository is only for the GenPipes documentation and it is not monitored as closely as our HelpDesk and bitbucket repository. For issues with GenPipes, it's best to contact us via one of the ways explained here: https://genpipes.readthedocs.io/en/genpipes-v4.4.2/support/how_to_get_support.html

I will take a look at the issue with the markname/mark_name variable. 

Best,
Mareike

**Comment by MareikeJaniak** [comment]
Hi Eric, 
The variable in the error message will be updated to `markname` in the next release of genpipes. Thanks for bringing it to our attention!
Best, 
Mareike
